apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: content
        image: content:0.1.0
        command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8080"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #   - name: app-volume
      #     mountPath: /app
      #     subPath: flask-app
      # volumes:
      # - name: app-volume
      #   persistentVolumeClaim:
      #     claimName: local-pvc
