kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio-testing
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31077
        hostPort: 31077
        listenAddress: "0.0.0.0" 
        protocol: tcp
      - containerPort: 32360
        hostPort: 32360
        listenAddress: "0.0.0.0" 
        protocol: tcp

        