apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-sc
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /volume/
