apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
