apiVersion: v1
kind: Service
metadata:
  name: images-service
spec:
  selector:
    app: images
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - name: images
        image: custom-nginx:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: image-volume
          mountPath: /usr/share/nginx/html/banners
          subPath: banners
          readOnly: true
      volumes:
      - name: image-volume
        persistentVolumeClaim:
          claimName: local-pvc
