apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                # override HTTP port to match kind's extraPortMappings,
                # this allows to communicate from host on
                # http://localhost:31077/productpage              
                - path: spec.ports.[name:http2].nodePort
                  value: 31077

                # HTTPS is not used at the moment,
                # override is here just in case
                - path: spec.ports.[name:https].nodePort
                  value: 32360
