apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-selfsigned-certificate
  namespace: istio-system
spec:
  dnsNames:
    - 'productpage.default.svc.cluster.local' # DNS name for the productpage service
  secretName: productpage-certificate # a descriptive name for the secret
  issuerRef:
    name: bookinfo-selfsigned-issuer
    kind: Issuer
